# -*- coding: utf-8 -*-
"""Preprocessing_SHIELD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FGzA32i-qRU5XhYIsHZc8xn7ya-AM1bP

# Step 1: Setup and General Data Information
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
file_path = 'data/bankruptcy_italian_companies_2023.xlsx'
df = pd.read_excel(file_path)

# 1. General Data Information
print("Dataset Shape:", df.shape)
print("\nMissing Values per column (Top 5):")
print(df.isnull().sum().sort_values(ascending=False).head())

# Preview the target class distribution
print("\nInitial Target Class Distribution:")
print(df['Bankrupt'].value_counts())

"""# Step 2: Data Cleaning and Target Label Mapping"""

# 2. Drop unique identifiers
if 'Company' in df.columns:
    df = df.drop(columns=['Company'])
    print("Dropped unique identifier column: 'Company'")

# Find and drop constant columns (columns where all values are exactly the same)
constant_cols = [col for col in df.columns if df[col].nunique() <= 1]
if constant_cols:
    df = df.drop(columns=constant_cols)
    print(f"Dropped constant columns: {constant_cols}")

# 3. Target Label Mapping
# Transform binary labels into categorical labels for interpretability
df['Bankrupt'] = df['Bankrupt'].map({0: 'Not Bankrupt', 1: 'Bankrupt'})

print("\nShape after cleaning:", df.shape)
print("Mapped Target Distribution:")
print(df['Bankrupt'].value_counts())

df.to_csv('data/df_cleaned_original.csv', index=False)

"""# Step 3: Feature Separation & Data Splitting"""

from sklearn.model_selection import train_test_split

# ==========================================
# EXPERIMENT TOGGLE: Change this value to test different splits!
# 0.20 = 80:20 split
# 0.30 = 70:30 split
TEST_SIZE = 0.20
# ==========================================

# Separate the features (X) and the target class (y)
X = df.drop(columns=['Bankrupt'])
y = df['Bankrupt']

# Split the data
# stratify=y ensures the bankrupt/not bankrupt ratio is maintained in both sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=TEST_SIZE, random_state=42, stratify=y
)

print(f"Current Split: {int(100 - (TEST_SIZE*100))}:{int(TEST_SIZE*100)}")
print(f"Training set features shape: {X_train.shape}")
print(f"Testing set features shape: {X_test.shape}")

"""# Step 4: Feature Selection via Information Gain (IG)"""

from sklearn.feature_selection import mutual_info_classif, SelectKBest
from functools import partial

# Calculate Information Gain (Mutual Information) on the training set
ig_scores = mutual_info_classif(X_train, y_train, random_state=42)

# Visualize the top features
ig_df = pd.DataFrame({'Feature': X_train.columns, 'IG_Score': ig_scores})
ig_df = ig_df.sort_values(by='IG_Score', ascending=False)
print("Top 10 Features by Information Gain:")
print(ig_df.head(10))

# Select the top 20 features (adjust 'k' as needed for your experiments)
k_features = 20
ig_scorer = partial(mutual_info_classif, random_state=42)

selector = SelectKBest(score_func=ig_scorer, k=k_features)

# Apply the selection to both training and testing sets
X_train_selected = selector.fit_transform(X_train, y_train)
X_test_selected = selector.transform(X_test)

# Get the names of the selected columns and convert back to DataFrames
selected_columns = X_train.columns[selector.get_support()]
X_train_sel_df = pd.DataFrame(X_train_selected, columns=selected_columns)
X_test_sel_df = pd.DataFrame(X_test_selected, columns=selected_columns)

print(f"\nSuccessfully isolated the top {k_features} predictive features.")
# Display all 20 selected features and their IG scores
print("All 20 Selected Features:")
display(ig_df.head(20))

"""# Step 5: Data Balancing via Synthetic Minority Over-Sampling Technique (SMOTE)"""

from imblearn.over_sampling import SMOTE

# Initialize SMOTE
smote = SMOTE(random_state=42)

# Apply SMOTE strictly to the pre-selected training data
X_train_balanced, y_train_balanced = smote.fit_resample(X_train_sel_df, y_train)

print("Class distribution BEFORE SMOTE:")
print(y_train.value_counts())

print("\nClass distribution AFTER SMOTE:")
print(y_train_balanced.value_counts())

# Convert targets back to numeric (0 and 1) for XGBoost compatibility
y_train_balanced_numeric = y_train_balanced.map({'Not Bankrupt': 0, 'Bankrupt': 1})
y_test_numeric = y_test.map({'Not Bankrupt': 0, 'Bankrupt': 1})

# Dynamically set filenames based on the split
split_name = f"{int(100 - (TEST_SIZE*100))}{int(TEST_SIZE*100)}"

# Save the final preprocessed datasets
X_train_balanced.to_csv(f'data/X_train_processed_{split_name}.csv', index=False)
y_train_balanced_numeric.to_csv(f'data/y_train_processed_{split_name}.csv', index=False)
X_test_sel_df.to_csv(f'data/X_test_processed_{split_name}.csv', index=False)
y_test_numeric.to_csv(f'data/y_test_processed_{split_name}.csv', index=False)

print(f"\nPipeline complete! Preprocessed datasets for {split_name} split are saved and ready.")

#SAVE ALL DATA
# Create a specific folder in your actual Google Drive
import os
drive_path = '/content/drive/MyDrive/SHIELD_Project/data'
os.makedirs(drive_path, exist_ok=True)

# Dynamically set filenames based on the split
split_name = f"{int(100 - (TEST_SIZE*100))}{int(TEST_SIZE*100)}"

# Save the final preprocessed datasets DIRECTLY TO GOOGLE DRIVE
X_train_balanced.to_csv(f'{drive_path}/X_train_processed_{split_name}.csv', index=False)
y_train_balanced_numeric.to_csv(f'{drive_path}/y_train_processed_{split_name}.csv', index=False)
X_test_sel_df.to_csv(f'{drive_path}/X_test_processed_{split_name}.csv', index=False)
y_test_numeric.to_csv(f'{drive_path}/y_test_processed_{split_name}.csv', index=False)

print(f"\nSaved permanently to Google Drive at: {drive_path}")

"""# Step 6: Final Dataset Verification"""

import pandas as pd

# Define the split you just processed to load the correct files
# Change this to '7030' if you run the 70:30 split experiment
split_name = '8020'

# 1. Load the processed datasets
X_train_final = pd.read_csv(f'data/X_train_processed_{split_name}.csv')
y_train_final = pd.read_csv(f'data/y_train_processed_{split_name}.csv')
X_test_final = pd.read_csv(f'data/X_test_processed_{split_name}.csv')
y_test_final = pd.read_csv(f'data/y_test_processed_{split_name}.csv')

# 2. Print Shape Verification
print("=== FINAL DATASET OVERVIEW ===")
print(f"Training Features Shape: {X_train_final.shape} (Expect 20 columns)")
print(f"Testing Features Shape: {X_test_final.shape} (Expect 20 columns)")

# 3. Verify Class Distributions
print("\n=== CLASS DISTRIBUTION VERIFICATION ===")
print("Training Set (Should be perfectly 50/50 due to SMOTE):")
print(y_train_final.value_counts())

print("\nTesting Set (Should remain imbalanced/untouched):")
print(y_test_final.value_counts())

# 4. Quick Data Preview
print("\n=== FEATURE PREVIEW ===")
print("Top 5 rows of X_train:")
display(X_train_final.head())